<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="1" failed="1" ignored="3" total="9" passed="4">
  <reporter-output>
    <line>
      <![CDATA[tc004  Executed]]>
    </line>
    <line>
      <![CDATA[tc005  Executed]]>
    </line>
    <line>
      <![CDATA[Tc008 executed]]>
    </line>
  </reporter-output>
  <suite name="default" duration-ms="97" started-at="2020-01-21T10:05:49 IST" finished-at="2020-01-21T10:05:49 IST">
    <groups>
      <group name="G1">
        <method signature="TestSuite1.tc001()[pri:0, instance:framework.Testng.Groups.TestSuite1@1f36e637]" name="tc001" class="framework.Testng.Groups.TestSuite1"/>
        <method signature="TestSuite3.tc007()[pri:0, instance:framework.Testng.Groups.TestSuite3@551aa95a]" name="tc007" class="framework.Testng.Groups.TestSuite3"/>
        <method signature="TestSuite3.tc009()[pri:0, instance:framework.Testng.Groups.TestSuite3@551aa95a]" name="tc009" class="framework.Testng.Groups.TestSuite3"/>
      </group> <!-- G1 -->
      <group name="G3">
        <method signature="TestSuite3.tc008()[pri:0, instance:framework.Testng.Groups.TestSuite3@551aa95a]" name="tc008" class="framework.Testng.Groups.TestSuite3"/>
        <method signature="TestSuite2.tc004()[pri:0, instance:framework.Testng.Groups.TestSuite2@578486a3]" name="tc004" class="framework.Testng.Groups.TestSuite2"/>
        <method signature="TestSuite2.tc005()[pri:0, instance:framework.Testng.Groups.TestSuite2@578486a3]" name="tc005" class="framework.Testng.Groups.TestSuite2"/>
      </group> <!-- G3 -->
    </groups>
    <test name="defult" duration-ms="97" started-at="2020-01-21T10:05:49 IST" finished-at="2020-01-21T10:05:49 IST">
      <class name="framework.Testng.Groups.TestSuite3">
        <test-method status="FAIL" signature="tc007()[pri:0, instance:framework.Testng.Groups.TestSuite3@551aa95a]" name="tc007" duration-ms="5" started-at="2020-01-21T10:05:49 IST" finished-at="2020-01-21T10:05:49 IST">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[did not expect to find [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: did not expect to find [true] but found [false]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.failNotEquals(Assert.java:969)
at org.testng.Assert.assertTrue(Assert.java:43)
at org.testng.Assert.assertTrue(Assert.java:53)
at framework.Testng.Groups.TestSuite3.tc007(TestSuite3.java:13)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tc007 -->
        <test-method status="PASS" signature="tc009()[pri:0, instance:framework.Testng.Groups.TestSuite3@551aa95a]" name="tc009" duration-ms="2" started-at="2020-01-21T10:05:49 IST" finished-at="2020-01-21T10:05:49 IST">
          <reporter-output>
            <line>
              <![CDATA[Tc008 executed]]>
            </line>
          </reporter-output>
        </test-method> <!-- tc009 -->
        <test-method status="SKIP" signature="tc008()[pri:0, instance:framework.Testng.Groups.TestSuite3@551aa95a]" name="tc008" duration-ms="0" depends-on-groups="G1" started-at="2020-01-21T10:05:49 IST" finished-at="2020-01-21T10:05:49 IST">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method TestSuite3.tc008()[pri:0, instance:framework.Testng.Groups.TestSuite3@551aa95a] depends on not successfully finished methods in group "G1"]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method TestSuite3.tc008()[pri:0, instance:framework.Testng.Groups.TestSuite3@551aa95a] depends on not successfully finished methods in group "G1"
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:99)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tc008 -->
      </class> <!-- framework.Testng.Groups.TestSuite3 -->
      <class name="framework.Testng.Groups.TestSuite2">
        <test-method status="PASS" signature="tc004()[pri:0, instance:framework.Testng.Groups.TestSuite2@578486a3]" name="tc004" duration-ms="3" started-at="2020-01-21T10:05:49 IST" finished-at="2020-01-21T10:05:49 IST">
          <reporter-output>
            <line>
              <![CDATA[tc004  Executed]]>
            </line>
          </reporter-output>
        </test-method> <!-- tc004 -->
        <test-method status="PASS" signature="tc005()[pri:0, instance:framework.Testng.Groups.TestSuite2@578486a3]" name="tc005" duration-ms="1" started-at="2020-01-21T10:05:49 IST" finished-at="2020-01-21T10:05:49 IST">
          <reporter-output>
            <line>
              <![CDATA[tc005  Executed]]>
            </line>
          </reporter-output>
        </test-method> <!-- tc005 -->
      </class> <!-- framework.Testng.Groups.TestSuite2 -->
      <class name="framework.Testng.Groups.TestSuite1">
        <test-method status="PASS" signature="tc001()[pri:0, instance:framework.Testng.Groups.TestSuite1@1f36e637]" name="tc001" duration-ms="17" started-at="2020-01-21T10:05:49 IST" finished-at="2020-01-21T10:05:49 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tc001 -->
      </class> <!-- framework.Testng.Groups.TestSuite1 -->
    </test> <!-- defult -->
  </suite> <!-- default -->
</testng-results>
